### ISSUE TITLE
Integrate events forms 

### ISSUE THREAD

**Issue by schlotterer** [schlotterer/flexline#8]
get events data in evnets form - js maybe?

**Comment by mattrocious** [comment]
AC:


Build data model to access event properties associated with Events:

Fields:
- email*
- first_name*
- last_name*
- phone
- number_attending*
-  preferred_contact
- optin*

Collected/created data points for future integrations:

event_formatted_date
event_formatted_time
event_category
event_url
event_number_attending
event_attendee_name
event_attendee_phone
event_attendee_email
event_post_id
event_end_date
event_recurrence
event_all_day

**Comment by schlotterer** [comment]
adding this to a plugin.
